POST http://127.0.0.1:10001/users/
Accept: application/json
Content-Type: application/json

{
  "username": "ssss",
  "password": "Pggg",
  "role": "user"
}

###

GET http://127.0.0.1:10001/users/
Accept: application/json

###

POST http://127.0.0.1:10001/auth/
Accept: application/json
Content-Type: application/json

{
  "username": "ssss",
  "password": "Pggg"
}
###

PUT http://127.0.0.1:10001/auth/
Accept: application/json
Content-Type: application/json

{
  "refresh_token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6Im9sZWciLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE2NDc3MjkwNDV9.-eeK5s4qxvdzEsIutBHG8FuO3zpFveBgyoyLPGvK4NU"
}

###